apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: custom.default
spec:
  groups:
    - system:authenticated
  request: <csr>
  signerName: kubernetes.io/kubelet-serving
  usages:
    - client auth