apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom
spec:
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: custom
        image: custom-controller:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: custom
spec:
  selector:
    app: custom
  ports:
    - port: 443